
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import { Inter } from 'next/font/google'
//import 'normalize.css/normalize.css'
import '@/styles/globals.css'

import styles from './layout.module.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'mvvb-app Home',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return  <html lang="fr">
      <body className={inter.className + ' ' + styles.body}>
        <Header/>
        <main className={styles.main}>
        {children}
        </main>
        <Footer/>
        </body>
    </html>
  
}
